# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5ef524a28e019fa59692626c4bfa16392f06173b7c495c0bb097ef9447830ec25e2e0b431b6e7566d3db93232e1e76f0d33dd0afa182646dbbdbdc434317d9

test:
  secret_key_base: f457fdd92581c9f92ea73bb9ba9935785f3521e10055937169b3f8271ac54efcddac110c5707a094f40d164c41b6e242f2368e20bd1fa3ac1608ac0c6f75510f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
